name: ML Training Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run training
      run: |
        python train.py | tee output/log.txt

    - name: Write Job Summary
      run: |
        echo "## Experiment Results" >> $GITHUB_STEP_SUMMARY
        echo "**Name:** Aditya Sri Ram Barnala" >> $GITHUB_STEP_SUMMARY
        echo "**Roll No:** 2022BCS0057" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        cat output/results.json >> $GITHUB_STEP_SUMMARY

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: experiment-artifacts
        path: output/
